<a href="https://colab.research.google.com/github/julianovale/MCDA/blob/main/0004_AHP_CristianoTorezzan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

FCA - UNICAMP

Disciplina: PO460: Métodos de Apoio à Decisão Multicritério

Introdução ao método **AHP**

In [ ]:
#Importando os pacotes do Python que serão utilizados
import numpy as np  # pacote numpy importado com o apelido de np
import cmath # pacote cmath faz operações com numeros complexos

In [ ]:
#Matriz de comparação par a par entre os critérios
C=[[1, 7, 7],[1/7, 1, 2],[1/7,1/2,1]]
C


[[1, 7, 7], [0.14285714285714285, 1, 2], [0.14285714285714285, 0.5, 1]]

In [ ]:
#Cálculo do autovalor e do autorvetor de C
autovalor, autovetor=np.linalg.eig(C)
#Considerar apenas a parte real do autovalor
autovalor_real = autovalor.real
autovetor = autovetor.real
print(autovalor_real)
print(" ")
print(autovetor.real)

[ 3.05362158 -0.02681079 -0.02681079]
 
[[ 0.97811392  0.97811392  0.97811392]
 [ 0.17604947 -0.08802474 -0.08802474]
 [ 0.11090422 -0.05545211 -0.05545211]]


In [ ]:
#Encontrar o maior autovalor e sua posição
lambda_max = np.amax(autovalor_real) # maior autovalor
lambda_ind=np.argmax(autovalor_real) # posição do maior autovalor
print("O maior autovalor (lambda_max) é:", lambda_max)
print(" ")
print("Ele está na posição:", lambda_ind, "do vetor")

O maior autovalor (lambda_max) é: 3.0536215758789713
 
Ele está na posição: 0 do vetor


In [ ]:
#Calculando o vetor de prioridades, com base no autovetor associado ao maior autovalor
vetor_P=autovetor[:, lambda_ind] #pega o autovalor correspondente a lambda_max
print(vetor_P)

#Normalizando o vetor_P para que tenha soma 1
vetor_P = vetor_P/sum(vetor_P) # w é o vetor de pesos normalizado
print(" ")
print(vetor_P)

[0.97811392 0.17604947 0.11090422]
 
[0.77317126 0.13916211 0.08766663]


In [ ]:
#Calculo da consistência da matriz de comparação par a par
RI_list = [0,0,0.58,0.90,1.12,1.24,1.32,1.41,1.45] # valores de RI pré-definidos
n = len(C) # número de linhas de C
CI = (lambda_max - n)/(n-1)
RC = CI/RI_list[n-1]

print("CI: ", CI)
print("RI: ", RI_list[n-1])
print("A razão de consistência é ", RC)
print(" ")
if RC <= 0.1:
  print("A matriz é consistente")
else:
  print('\033[91m'+"Atenção:"+'\033[0m'+ "a matriz NÃO É consistente - revisar a comparação par-a-par.")


CI:  0.02681078793948566
RI:  0.58
A razão de consistência é  0.04622549644738907
 
A matriz é consistente


In [ ]:
#Após calcular todos os vetores de prioridade, a agregação pode ser feita multiplicando as matrizes B pelo vetor de pesos w
B = [[1,1,1],[1,1,1],[1,1,1],[1,1,1]]
w = [0.55842454, 0.31961826, 0.12195719]
V=np.matmul(B, w)
print(V)

[0.99999999 0.99999999 0.99999999 0.99999999]


In [ ]:
#Programando o método do autovalor como uma função
def ahp(C):
  autovalor, autovetor=np.linalg.eig(C)
  autovalor_real = autovalor.real
  autovetor = autovetor.real
  lambda_max = np.amax(autovalor_real) # maior autovalor
  lambda_ind=np.argmax(autovalor_real) # posição do maior autovalor
  vetor_P=autovetor[:, lambda_ind] #pega o autovalor correspondente a lambda_max
  vetor_P = vetor_P/sum(vetor_P) # w é o vetor de pesos normalizado
  RI_list = [0,0,0.58,0.90,1.12,1.24,1.32,1.41,1.45] # valores de RI pré-definidos
  n = len(C) # número de linhas de C
  CI = (lambda_max - n)/(n-1)
  RC = CI/RI_list[n-1]
  print("CI: ", CI)
  print("RI: ", RI_list[n-1])
  print("A razão de consistência é ", RC)
  print(" ")
  if RC <= 0.1:
    print("A matriz é consistente")
  else:
    print('\033[91m'+"Atenção:"+'\033[0m'+ "a matriz NÃO É consistente - revisar a comparação par-a-par.")
  print(" ")
  print("O vetor de prioridades é v:", vetor_P)
  print(" ")


In [ ]:
ahp(C)


CI:  0.02681078793948566
RI:  0.58
A razão de consistência é  0.04622549644738907
 
A matriz é consistente
 
O vetor de prioridades é v: [0.77317126 0.13916211 0.08766663]
 


In [ ]:
preco = [[1,0.3333,0.2,0.1428],[3,1,0.3333,0.2],[5,3,1,0.2],[7,5,5,1]]
nota = [[1,3,2,7],[0.3333,1,0.5,5],[0.5,2,1,6],[0.1428,0.2,0.1666,1]]
localizacao = [[1,2,5,4],[0.5,1,4,2],[0.2,0.25,1,0.5],[0.25,0.5,2,1]]

In [ ]:
ahp(preco)


CI:  0.08006139329039463
RI:  0.9
A razão de consistência é  0.08895710365599403
 
A matriz é consistente
 
O vetor de prioridades é v: [0.05206145 0.10901511 0.21950489 0.61941855]
 


In [ ]:
ahp(nota)


CI:  0.025441234805671325
RI:  0.9
A razão de consistência é  0.02826803867296814
 
A matriz é consistente
 
O vetor de prioridades é v: [0.47842674 0.18006525 0.29179126 0.04971675]
 


In [ ]:
ahp(localizacao)


CI:  0.009246313859649172
RI:  0.9
A razão de consistência é  0.010273682066276858
 
A matriz é consistente
 
O vetor de prioridades é v: [0.50079316 0.27993237 0.0793083  0.13996618]
 
