<a href="https://colab.research.google.com/github/julianovale/MADC/blob/main/AHP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

FCA - UNICAMP

Disciplina: PO460: Métodos de Apoio à Decisão Multicritério

Introdução ao método **AHP**

In [1]:
#Importando os pacotes do Python que serão utilizados
import numpy as np  # pacote numpy importado com o apelido de np
import cmath # pacote cmath faz operações com numeros complexos

In [2]:
#Matriz de comparação par a par entre os critérios
C=[[1, 2, 4],[1/2, 1, 3],[1/4,1/3,1]]


In [4]:
#Cálculo do autovalor e do autorvetor de C
autovalor, autovetor=np.linalg.eig(C)
#Considerar apenas a parte real do autovalor
autovalor_real = autovalor.real
autovetor = autovetor.real
print(autovalor_real)
print(" ")
print(autovetor.real)

[ 3.01829471 -0.00914735 -0.00914735]
 
[[ 0.85271323  0.85271323  0.85271323]
 [ 0.48805649 -0.24402824 -0.24402824]
 [ 0.1862284  -0.0931142  -0.0931142 ]]


In [5]:
#Encontrar o maior autovalor e sua posição
lambda_max = np.amax(autovalor_real) # maior autovalor
lambda_ind=np.argmax(autovalor_real) # posição do maior autovalor
print("O maior autovalor (lambda_max) é:", lambda_max)
print(" ")
print("Ele está na posição:", lambda_ind, "do vetor")

O maior autovalor (lambda_max) é: 3.01829470728963
 
Ele está na posição: 0 do vetor


In [ ]:
#Calculando o vetor de prioridades, com base no autovetor associado ao maior autovalor
vetor_P=autovetor[:, lambda_ind] #pega o autovalor correspondente a lambda_max
print(vetor_P)

#Normalizando o vetor_P para que tenha soma 1
vetor_P = vetor_P/sum(vetor_P) # w é o vetor de pesos normalizado
print(" ")
print(vetor_P)

[0.85271323 0.48805649 0.1862284 ]
 
[0.55842454 0.31961826 0.12195719]


In [ ]:
#Calculo da consistência da matriz de comparação par a par
RI_list = [0,0,0.58,0.90,1.12,1.24,1.32,1.41,1.45] # valores de RI pré-definidos
n = len(C) # número de linhas de C
CI = (lambda_max - n)/(n-1)
RC = CI/RI_list[n-1]

print("A razão de consistência é ", RC)
print(" ")
if RC <= 0.1:
  print("A matriz é consistente")
else:
  print('\033[91m'+"Atenção:"+'\033[0m'+ "a matriz NÃO É consistente - revisar a comparação par-a-par.")


A razão de consistência é  0.015771299387612077
 
A matriz é consistente


In [ ]:
#Após calcular todos os vetores de prioridade, a agregação pode ser feita multiplicando as matrizes B pelo vetor de pesos w
B = [[1,1,1],[1,1,1],[1,1,1],[1,1,1]]
w = [0.55842454, 0.31961826, 0.12195719]
V=np.matmul(B, w)
print(V)

[0.99999999 0.99999999 0.99999999 0.99999999]


In [ ]:
#Programando o método do autovalor como uma função
def ahp(C):
  autovalor, autovetor=np.linalg.eig(C)
  autovalor_real = autovalor.real
  autovetor = autovetor.real
  lambda_max = np.amax(autovalor_real) # maior autovalor
  lambda_ind=np.argmax(autovalor_real) # posição do maior autovalor
  vetor_P=autovetor[:, lambda_ind] #pega o autovalor correspondente a lambda_max
  vetor_P = vetor_P/sum(vetor_P) # w é o vetor de pesos normalizado
  RI_list = [0,0,0.58,0.90,1.12,1.24,1.32,1.41,1.45] # valores de RI pré-definidos
  n = len(C) # número de linhas de C
  CI = (lambda_max - n)/(n-1)
  RC = CI/RI_list[n-1]
  print("A razão de consistência é ", RC)
  print(" ")
  if RC <= 0.1:
    print("A matriz é consistente")
  else:
    print('\033[91m'+"Atenção:"+'\033[0m'+ "a matriz NÃO É consistente - revisar a comparação par-a-par.")
  print(" ")
  print("O vetor de prioridades é v:", vetor_P)
  print(" ")


In [ ]:
ahp(C)

A razão de consistência é  0.015771299387612077
 
A matriz é consistente
 
O vetor de prioridades é v: [0.55842454 0.31961826 0.12195719]
 
